### ISSUE TITLE
Sliding only works on the first click.

### ISSUE THREAD

**Issue by jculloty** [andyyou/react-coverflow#45]
The first image clicked will slide to the centre; after that clicking on an image has no effect.
Removing this code

// this.refs.stage.style['pointerEvents'] = 'none';

 from lime 247 appears to solve the problem.

**Comment by Asalem1** [comment]
Hey @jculloty , thanks for brining this issue up. I'll take a look at this.

**Comment by Asalem1** [comment]
Quick update on these tickets. I came across some dependency issues when I ran it locally, so I'm going to be updating the repo in order to get everything up to date. I'll keep you updated on the state of affairs going forward

**Comment by Asalem1** [comment]
Fixed with newest release

**Comment by revgum** [comment]
This bug still exists in 0.2.18 `master` as of today. I removed the line and everything works fine otherwise. FWIW, here is my basic structure of the items in the coverflow

```
Coverflow
  div onClick={e=>this.clickHandler(e)}
    img
```

**Comment by Asalem1** [comment]
@revgum thanks for the PR! Looks great
